<?php 
use ContentinumComponents\Html\HtmlTable;
use ContentinumComponents\Html\Table\FactoryTable;

$tableFactory = new HtmlTable ( new FactoryTable () );

// set table tag attributes
$tableFactory->setAttributes ( 'class', 'table table-hover table-nomargin table-striped dataTable dataTable-tools' );
$i = 0;
$iClass = 0;
$headlines = array (
        '#' => array(),
		'Account' => array (),
		'Ident' => array (
				'head' => array (
						'class' => 'hide-for-small text-right' 
				),
				'body' => array (
						'class' => 'hide-for-small text-right' 
				) 
		),
		'Registerd since' => array (
				'head' => array (
						'class' => 'hide-for-small text-right' 
				),
				'body' => array (
						'class' => 'hide-for-small text-right' 
				) 
		)
		 
);
$ihead = count ( $headlines );
foreach ( $headlines as $column => $attributes ) {
	$columns [] = $this->translate ( $column );
	if (is_array ( $attributes ) && ! empty ( $attributes )) {
		foreach ( $attributes as $area => $attribute ) {
			switch ($area) {
				case 'head' :
					$tableFactory->setHeadlineAttributtes ( 'class', $attribute ['class'], $i );
					break;
				case 'body' :
					$tableFactory->setTagAttributtes ( 'class', $attribute ['class'], $i );
					break;
				default :
					break;
			}
		}
	}
	$i ++;
}
$tableFactory->setHeadline ( $columns );
$i = 0;
foreach ( $this->entries as $entry ) {

		
		$i ++;
		$rowContent = array ();
		$rowContent[] = '<input type="checkbox" value="'.$entry->id.'" name="cb[]">';
		$rowContent [] = $entry->organisation;// . $this->mcworkTableEdit ( $tbl );
		$rowContent [] = $entry->accountName;
		$rowContent [] = $entry->registerDate->format('d F Y H:i:s'); // date ( "d.m.Y H:i:s", $entry->registerDate );
		$tableFactory->setHtmlContent ( $rowContent );
	
}

$html = $tableFactory->display ();
$html .= $this->translate ( $this->mcworkContent ( $this->page, $this->pagecontent, 'content' ) );

if (isset ( $this->widget )) {
	$content = str_replace ( '{TEMPLATE_HEAD}', $this->translate ( $this->mcworkContent ( $this->page, $this->pagecontent, 'subheadline' ) ), $this->widget );
	echo str_replace ( '{TEMPLATE_CONTENT}', $html, $content );
} else {
	echo $this->translate ( $this->mcworkContent ( $this->page, $this->pagecontent, 'subheadline' ) );
	echo $html;
}
?>