<?php
/**
 * contentinum - accessibility websites
 *
 * LICENSE
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @category contentinum backend
 * @package View
 * @author Michael Jochum, michael.jochum@jochum-mediaservices.de
 * @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
 * @license http://www.opensource.org/licenses/bsd-license
 * @since contentinum version 5.0
 * @link      https://github.com/Mikel1961/contentinum-components
 * @version   1.0.0
 */
use ContentinumComponents\Html\HtmlTable;
use ContentinumComponents\Html\Table\FactoryTable;

// prepare content, create a table
$tableFactory = new HtmlTable(new FactoryTable());
$ctrlpath = 'menue';
// set table tag attributes
$tableFactory->setAttributes('class', 'table tblNoSort');// table-hover table-nomargin table-striped dataTable dataTable-tools');
$tableFactory->setAttributes('id', 'mcworkTables');
$i = 0;
$iClass = 0;//sorting_disabled
$headlines = array(
    '#' => array(),
    'Page' => array(),
    'Sequence' => array(),
    'Rang' => array(
        'head' => array(
            'class' => 'text-center'
        ),
        'body' => array(
            'class' => 'text-center'
        )    
    ),
    'Navigation' => array(),
    'Branch' => array(),
    'Access rights' => array(),
    'Publish' => array(
        'head' => array(
            'class' => 'text-center'
        ),
        'body' => array(
            'class' => 'text-center'
        )        
    ),
    'Edit' => array(
        'head' => array(
            'class' => 'hide-for-small text-right'
        ),
        'body' => array(
            'class' => 'hide-for-small text-right'
        )
    )
);
$ihead = count($headlines);
foreach ($headlines as $column => $attributes) {
    $columns[] = $this->translate($column);
    if (is_array($attributes) && ! empty($attributes)) {
        foreach ($attributes as $area => $attribute) {
            switch ($area) {
                case 'head':
                    $tableFactory->setHeadlineAttributtes('class', $attribute['class'], $i);
                    break;
                case 'body':
                    $tableFactory->setTagAttributtes('class', $attribute['class'], $i);
                    break;
                default:
                    break;
            }
        }
    }
    $i ++;
}
$tableFactory->setHeadline($columns);
$i = 0;
$defaults = $this->toolbarcontent->toArray();
$editDefaults = $defaults;
$defaults['attribute']['class'] = 'button-group left';

$rangSelect = count($this->entries);

foreach ($this->entries as $entry) {
    $i ++;
    $tbl = array(
        'up' => array(
            'attribs' => array(
                'data-group' => $entry->webNavigations->id,
                'data-category' => $entry->id,
                'data-rang' => $entry->itemRang,
                'data-categoryname' => 'Categories\Navigation',
                'data-move' => 'moveup',
                'class' => 'button tiny moveitem'
            )
        ),        
        'down' => array(
            'attribs' => array(
                'data-group' => $entry->webNavigations->id,
                'data-category' => $entry->id,
                'data-rang' => $entry->itemRang,
                'data-categoryname' => 'Categories\Navigation',
                'data-move' => 'movedown',
                'class' => 'button tiny moveitem'
            )
        ), 
    );
    if (1 == $i){
        unset($tbl['up']);
    }
    if ($i == $rangSelect){
        unset($tbl['down']);
    }
    $rowContent = array();
    $rowContent[] = '<input id="row' . $i . '" type="checkbox" value="' . $entry->id . '" name="cb[]" data-name="'.$entry->webPages->label.'" data-categoryname="Categories\Navigation" data-model="Remove" data-group="' . $entry->webNavigations->id . '">';
    $rowContent[] = $entry->webPages->label;
    $rowContent[] = $this->mcworkToolbar($tbl, true, $defaults);  
    $rowContent[] = $this->mcworkSelectRang($entry->webNavigations->id,$entry->id,$entry->itemRang, $rangSelect, 'Categories\Navigation');
    $rowContent[] = $entry->webNavigations->title; 
    
    if ($entry->parentFrom > '0'){
        $str = '<ul class="button-group">';
        $str .= '<li><a class="button tiny success" href="/mcwork/menue/category/' . $entry->parentFrom;
        $str .= '" role="button"><i class="fa fa-pencil"> </i></a></li>';
        $str .= '<li><a title="'. $this->translate('Unhook this navigation branch') .'" class="button tiny alert removesub" ';
        $str .= 'href="#" data-ident="' . $entry->id . '" data-parent="'.$entry->parentFrom.'" ';
        $str .= 'data-pageident="' . $entry->webPages->id . '" ';
        $str .= 'data-scope="' . $entry->webPages->scope . '" ';
        $str .= 'data-label="' . $entry->webPages->label . '" ';
        $str .= '" role="button"><i class="fa fa-minus"> </i></a></li>';
        $str .= '</ul>';
    } else {
        $str = '<a class="button tiny addsubmenue" href="#" ';
        $str .= 'data-label="' . $entry->webPages->label . '" ';
        $str .= 'data-ident="' . $entry->id . '" ';
        $str .= 'data-scope="' . $entry->webPages->scope . '" ';
        $str .= 'data-pageident="' . $entry->webPages->id . '">';
        $str .= '<i class="fa fa-plus"> </i></a>';
    }
    $rowContent[] = $str;
    $rowContent[] = $entry->resource;
    $rowContent[] = $this->mcworkPublishItem($entry->publish,$entry->id,'Categories\Navigation');
    $props = array(
        'edit' => array(
            'href' => '/mcwork/' . $ctrlpath . '/edit/' . $entry->id,
            'attribs' => array(
                'title' => 'Edit item',
                'class' => 'button tiny'
            )
        ),
        'remove' => array(
            'href' => '/mcwork/' . $ctrlpath . '/detach',
            'attribs' => array(
                'data-name' => $entry->webPages->label,
                'data-ident' => 'row' . $i,
                'title' => 'Remove item',
                'class' => 'button tiny alert removeitem'
            )
        ),
        'info' => array(
            'attribs' => array(
                'data-update' => $entry->upDate->format('d F Y, H:i:s'),
                'data-registerdate' => $entry->registerDate->format('d F Y, H:i:s'),
                'data-role' => $this->role,
                'title' => 'Delete item',
                'class' => 'button tiny infotip'
            )
        )        
    );    
    if ($entry->parentFrom > '0'){
        unset($props['remove']);
    }
    
    $rowContent[] = $this->mcworkToolbar($props, true, $editDefaults );
    $tableFactory->setHtmlContent($rowContent);
}
$table = $tableFactory->display();
if (true === $this->onlytable){
    echo $table;
    exit();
}
$html = '<div id="setDataTable"> '. $table . ' </div>';
$html .= $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'content'));
$toolbar = '';
if (isset($this->toolbarcontent)) {
    $links = array(
        'add' => array(
            'href' => '/mcwork/' . $ctrlpath . '/add/' . $this->category
        ),
        'edit' => array(
            'href' => '/mcwork/' . $ctrlpath . '/edit'
        ),
        'remove' => array(
            'href' => '/mcwork/' . $ctrlpath . '/detach'
        ),
        'back' => array(
            'href' => ($this->category > 1) ? '/mcwork/menue/category/1' : '/mcwork/navigation'
        )        
    );
    $toolbar = $this->mcworkToolbar($links, true, $this->toolbarcontent->toArray());
}
// output, display content
if (isset($this->widget)) {
    $content = str_replace('{TEMPLATE_HEADER}', $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'subheadline')) . $toolbar, $this->widget);
    echo str_replace('{TEMPLATE_CONTENT}', $html, $content);
} else {
    echo $this->translate($this->mcworkContent($this->page, $this->pagecontent, 'subheadline'));
    echo $html;
}
?>