<div class="box"><div class="box-title">
<h3><i class="icon-reorder"></i> <?php echo $this->translate($this->mcworkContent( $this->page, $this->pagecontent,'subheadline')); ?> </h3>
</div><div class="box-content nopadding"><div id="foldermediasfiles"><section id="filescrollarea">
<?php
echo $this->mediasTableView($this->entries);
$up = '';
if ($this->currentFolder) {
    $up = '/' . str_replace(DS, $this->seperator, $this->currentFolder);
}
?>
</section>
<p><?php echo $this->translate('max_upload') .  ' ['. ini_get('upload_max_filesize'); ?>]</p>
<form id="contentinumUpload" action="/mcwork/medias/upload<?php echo $up; ?>" method="post" enctype="multipart/form-data" class="dropzone"><div class="fallback"><input name="file" type="file" multiple /></div></form>
</div>
<?php 
echo $this->translate($this->mcworkContent( $this->page, $this->pagecontent,'content'));
?>
<p>
<button id="btnSelect" class="small button" data-status="unselect"><?php echo $this->translate('Select All'); ?></button>
<button id="btnCopy" class="small button"><?php echo $this->translate('Copy'); ?></button>
<button id="btnMove" class="small button"><?php echo $this->translate('Move'); ?></button>
<button id="btnZip" class="small button"><?php echo $this->translate('Zip'); ?></button>
<button id="btnDelete" class="small button"><?php echo $this->translate('Delete'); ?></button>
</p>
</div></div>