<?php
/**
 * contentinum - accessibility websites
*
* LICENSE
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
* LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
		* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
		* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
* @category contentinum backend
* @package View
* @author Michael Jochum, michael.jochum@jochum-mediaservices.de
* @copyright Copyright (c) 2009-2013 jochum-mediaservices, Katja Jochum (http://www.jochum-mediaservices.de)
* @license http://www.opensource.org/licenses/bsd-license
* @since contentinum version 5.0
* @link      https://github.com/Mikel1961/contentinum-components
* @version   1.0.0
*/

$up = '';
if ($this->currentFolder) {
	$up = '/' . str_replace(DS, $this->seperator, $this->currentFolder);
}
$attrData = ' data-action="/mcwork/medias/upload' . $up . '"';
$attrData .= ' data-maxfilesize="' . ini_get('upload_max_filesize') . '"';
$attrData .= ' data-currentfolder="' . $this->currentFolder .'"';
?>

<div id="clNewFolder" class="row collapse">
    <div class="small-9 columns">
        <input id="new-folder" type="text"><span class="errNewFolder"> </span>
        </div>
        <div class="small-3 columns">
        <a id="btnNewFolder" href="#" class="button postfix"><?php echo $this->translate('New Folder'); ?></a>
    </div>
</div>
<div class="box"><div class="box-title toolbar">
<h3><i class="fa fa-recorder"></i> <?php echo $this->translate($this->mcworkContent( $this->page, $this->pagecontent,'subheadline')); ?> </h3>
<ul class="button-group right">
    <li><button id="btnUpload" class="small button" <?php echo $attrData;  ?>><?php echo $this->translate('Upload'); ?></button></li>
	<li><button id="btnSelect" class="small button" data-status="unselect"><?php echo $this->translate('Select All'); ?></button></li>
	<li><button id="btnCopy" class="small button"><?php echo $this->translate('Copy'); ?></button></li>
	<li><button id="btnMove" class="small button"><?php echo $this->translate('Move'); ?></button></li>
	<li><button id="btnZip" class="small button"><?php echo $this->translate('Zip'); ?></button></li>
	<li><button id="btnDelete" class="small button"><?php echo $this->translate('Delete'); ?></button></li>
</ul>
</div><div class="box-content nopadding"><div id="foldermediasfiles"><section id="filescrollarea">
<?php
echo $this->mediasTableView($this->entries, $this->mediatable, $this->inusemedias);
?>
</section></div>
<?php
echo $this->translate($this->mcworkContent( $this->page, $this->pagecontent,'content'));
?>
</div>
</div>