<?php
echo '<section id="filescrollarea">';
echo $this->mediasTableView($this->entries);
$up = '';
if ($this->currentFolder) {
	$up = '/' . str_replace(DS, $this->seperator, $this->currentFolder);
}
echo '</section>';
echo '<form id="contentinumUpload" action="/mcwork/medias/upload' . $up .'" method="post" enctype="multipart/form-data" class="dropzone"><div class="fallback"><input name="file" type="file" multiple /></div></form>';
exit();
?>