<?php echo $this->doctype(); ?>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html<?php echo $this->htmlTagAttribs; ?>> <!--<![endif]-->
<head>
<meta charset="utf-8">
<?php 
echo $this->headTitle()->setAutoEscape(false) . "\n";
echo $this->headMeta() . "\n";
echo $this->headlink()  . "\n";
echo $this->headScript()  . "\n";
?>
</head>
<body<?php echo $this->bodyTagAttribs; ?>>
<?php
echo $this->content;     
echo "\n" . $this->inlineScript(); 
?>
</body>
</html>