<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en" >
<!--<![endif]-->
<head>
<meta charset="utf-8">
<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
<title>contentinum 5</title>
<?php 
echo $this->plugin('HeadLink');
echo $this->plugin('HeadStyle');
echo $this->plugin('HeadScript');
?>
</head>
<body<?php echo $this->bodyAttributes ?>>
<nav class="top-bar">
<ul class="title-area"><li class="name"><h1><a href="#"><i class="icon-dashboard"></i> contentinum 5 </a></h1></li><li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li></ul>
<section class="top-bar-section">
<?php 
$container = $this->navigation('navigation')->getContainer();
echo $this->ContentinumMenue($container)->setAcl($this->acl)->setRole($this->role)->setUlClass('right');
?>
</section>
</nav>
<header class="row">
<section class="large-6 columns"><h1>Dashboard</h1></section>
<section class="large-6 columns"><p>hier header</p></section>
</header>
<section class="large-12 columns">
<?php echo $this->content; ?>
</section>
<?php echo $this->plugin('InlineScript'); ?>
</body>
</html>